use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use anyhow::Context;
use log::{debug, warn};

const HYPR_CONFIG_DIR: &str = "hypr";
const WALT_HYPRPAPER_CONFIG_FILE: &str = "hyprpaper-walt.conf";

const FILE_HEADER: &str = "\
# Generated by Walt. Changes made here are overwritten whenever Walt applies a wallpaper.
# Restore Walt's wallpapers when hyprpaper starts by adding this line to hyprpaper.conf:
#   source = ~/.config/hypr/hyprpaper-walt.conf
";

pub fn walt_hyprpaper_config_path() -> Option<PathBuf> {
    dirs::config_dir().map(|dir| dir.join(HYPR_CONFIG_DIR).join(WALT_HYPRPAPER_CONFIG_FILE))
}

pub fn persist_wallpaper_assignments(assignments: &[(String, PathBuf)]) {
    if assignments.is_empty() {
        return;
    }

    let Some(path) = walt_hyprpaper_config_path() else {
        warn!("skipping hyprpaper config persistence because the config directory is unknown");
        return;
    };

    match update_config_file(&path, assignments) {
        Ok(()) => debug!(
            "persisted wallpaper assignments count={} path={}",
            assignments.len(),
            path.display()
        ),
        Err(error) => warn!(
            "failed to persist wallpaper assignments path={} error={error:#}",
            path.display()
        ),
    }
}

fn update_config_file(path: &Path, assignments: &[(String, PathBuf)]) -> anyhow::Result<()> {
    let path = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    let existing = fs::read_to_string(&path).unwrap_or_default();

    let mut entries = parse_config(&existing);
    for (monitor_name, wallpaper_path) in assignments {
        entries.insert(monitor_name.clone(), absolute_path(wallpaper_path));
    }

    let dir = path
        .parent()
        .context("hyprpaper config path has no parent directory")?;
    fs::create_dir_all(dir).with_context(|| format!("failed to create {}", dir.display()))?;

    let tmp_path = path.with_extension("conf.tmp");
    fs::write(&tmp_path, render_config(&entries))
        .with_context(|| format!("failed to write {}", tmp_path.display()))?;
    fs::rename(&tmp_path, &path)
        .with_context(|| format!("failed to replace {}", path.display()))?;
    Ok(())
}

fn absolute_path(path: &Path) -> PathBuf {
    fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}

fn parse_config(content: &str) -> BTreeMap<String, PathBuf> {
    let mut entries = BTreeMap::new();
    let mut in_block = false;
    let mut monitor = None;
    let mut wallpaper = None;

    for line in content.lines() {
        let line = strip_comment(line);
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        if !in_block {
            if let Some(rest) = line.strip_prefix("wallpaper") {
                if rest.trim() == "{" {
                    in_block = true;
                    monitor = None;
                    wallpaper = None;
                }
            }
            continue;
        }

        if line == "}" {
            if let (Some(monitor), Some(wallpaper)) = (monitor.take(), wallpaper.take()) {
                entries.insert(monitor, wallpaper);
            }
            in_block = false;
            continue;
        }

        if let Some((key, value)) = line.split_once('=') {
            let value = value.trim();
            match key.trim() {
                "monitor" => monitor = Some(value.to_string()),
                "path" if !value.is_empty() => wallpaper = Some(PathBuf::from(value)),
                _ => {}
            }
        }
    }

    entries
}

fn strip_comment(line: &str) -> String {
    let mut result = String::with_capacity(line.len());
    let mut chars = line.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch == '#' {
            if chars.peek() == Some(&'#') {
                chars.next();
                result.push('#');
            } else {
                break;
            }
        } else {
            result.push(ch);
        }
    }
    result
}

fn escape_value(value: &str) -> String {
    value.replace('#', "##")
}

fn render_config(entries: &BTreeMap<String, PathBuf>) -> String {
    let mut output = String::from(FILE_HEADER);
    for (monitor, wallpaper) in entries {
        output.push_str(&format!(
            "\nwallpaper {{\n    monitor = {}\n    path = {}\n}}\n",
            escape_value(monitor),
            escape_value(&wallpaper.to_string_lossy())
        ));
    }
    output
}

#[cfg(test)]
mod tests {
    use super::{parse_config, render_config, update_config_file};
    use std::{collections::BTreeMap, fs, path::PathBuf};

    #[test]
    fn round_trips_rendered_config() {
        let mut entries = BTreeMap::new();
        entries.insert("DP-1".to_string(), PathBuf::from("/walls/alpha.jpg"));
        entries.insert("HDMI-A-1".to_string(), PathBuf::from("/walls/#1 beta.png"));

        let rendered = render_config(&entries);
        assert!(rendered.contains("path = /walls/##1 beta.png"));
        assert_eq!(parse_config(&rendered), entries);
    }

    #[test]
    fn ignores_incomplete_blocks_and_unrelated_keys() {
        let entries = parse_config(
            "splash = false\n\
             wallpaper {\n    monitor = DP-1\n}\n\
             wallpaper {\n    monitor = DP-2\n    path = /walls/a.jpg # note\n    fit_mode = cover\n}\n",
        );

        assert_eq!(
            entries,
            BTreeMap::from([("DP-2".to_string(), PathBuf::from("/walls/a.jpg"))])
        );
    }

    #[test]
    fn merges_new_assignments_and_keeps_other_monitors() {
        let dir =
            std::env::temp_dir().join(format!("walt-hyprpaper-config-{}", std::process::id()));
        let path = dir.join("hyprpaper-walt.conf");
        let _ = fs::remove_dir_all(&dir);

        update_config_file(
            &path,
            &[
                ("DP-1".to_string(), PathBuf::from("/walls/a.jpg")),
                ("DP-2".to_string(), PathBuf::from("/walls/b.jpg")),
            ],
        )
        .expect("initial write should succeed");
        update_config_file(
            &path,
            &[("DP-2".to_string(), PathBuf::from("/walls/c.jpg"))],
        )
        .expect("update should succeed");

        let entries = parse_config(&fs::read_to_string(&path).expect("config should exist"));
        let _ = fs::remove_dir_all(&dir);

        assert_eq!(
            entries,
            BTreeMap::from([
                ("DP-1".to_string(), PathBuf::from("/walls/a.jpg")),
                ("DP-2".to_string(), PathBuf::from("/walls/c.jpg")),
            ])
        );
    }
}
